#! /usr/bin/env node
'use strict';

const util = require('util');
const exec = util.promisify(require('child_process').exec);
const { execSync } = require('child_process');

async function a(arg) {
  const { stdout, stderr } = await exec(arg);

  console.log('stdout:', stdout);
  console.log('stderr:', stderr);
}

a('ls');

const diff = execSync('git --no-pager  log origin/master..staging --oneline --grep "Merge pull request"', {
  encoding: 'utf-8',
});

console.log({ diff });