#! /usr/bin/env node
'use strict';

const { execSync } = require('child_process');
const { compose, head, map, replace, match, pick, trim } = require('ramda');
const dotenv = require('dotenv');
const { getCardsWithListId } = require('../helpers/coca');

dotenv.config();

const options = { encoding: 'utf-8', stdio : 'pipe' };

const GOOGLE_SHEET_DATA = `
AttachmentChip.style.js,
AttachmentList.style.js,
Avatar.style.js,
Badge.style.js,
BlastedGroup.style.js,
BlastedGroups.style.js,
Button.style.js,
ChatroomUserRow.style.js,
Chip.style.js,
CompanyContactDialog.style.js,
ContextHeader.style.js,
CreateChatroomMessageForm.style.js,
DeactivatedChatroomBanner.style.js,
DeactivatedContainer.style.js,
DefensiveContainer.style.js,
DialogSlide.style.js,
DirectChatroomListDialog.style.js,
DirectMessageDialog.style.js,
DirectMessagesBadge.style.js,
Divider.style.js,
MentionButton.style.js,
PreferredContact.style.js,
Document.style.js,
DragAndDropZone.style.js,
Dropdown.style.js,
EmptyPlaceholder.style.js,
Feed.style.js,
FeedItemMessageInformation.style.js,
FeedSkeleton.style.js,
Filter.style.js,
FiltersStateBar.style.js,
FlagshipFund.style.js,
GroupFeed.style.js,
GroupFeedItem.style.js,
Message.style.js,
Option.style.js,
RecipientRow.style.js,
UserList.style.js,
Header.style.js,
HeaderSearchBar.style.js,
Headline1.style.js,
Headline2.style.js,
Layout.style.js,
MentionFundSuggestion.style.js,
MentionSuggestion.style.js,
Navigation.style.js,
SetPassword.style.js,
BlastRecipientSearchBar.style.js,
CreateFormButton.style.js,
Footer.style.js,
MenuItem.style.js,
MessageCount.style.js,
MessageCreateForm.style.js,
MessageInformation.style.js,
MonoBlast.style.js,
NewDefensiveContainer.style.js,
NewNotificationsBadge.style.js,
NewsRecipient.style.js,
NewsRecipientSearchBar.style.js,
Notification.style.js,
Notifications.style.js,
OutblastBanner.style.js,
PageHeader.style.js,
Paragraph.style.js,
Post.style.js,
PostCreateForm.style.js,
PostZone.style.js,
Recipient.style.js,
RecipientList.style.js,
ResendOutblastBanner.style.js,
ResentOutblastBanner.style.js,
AboutNews.style.js,
ActivityUserRow.style.js,
AttachmentChip.style.js,
Characteristics.style.js,
Clients.style.js,
ClientsFundPicksTable.style.js,
ClientsTable.style.js,
Companies.style.js,
CompaniesTable.style.js,
CompaniesTableCell.style.js,
Company.style.js,
ContactBanner.style.js,
DangerousText.style.js,
DescriptionSection.style.js,
Documents.style.js,
DocumentSection.style.js,
DocumentsTab.style.js,
DueDiligenceDocuments.style.js,
DueDiligenceDocuments.style.js,
ExternalFilters.style.js,
ExternalFiltersContent.style.js,
ExternalFiltersHeadline.style.js,
ExternalFiltersMobileDialog.style.js,
Fees.style.js,
FlagshipFunds.style.js,
ForgotPassword.style.js,
ForgotPasswordSuccess.style.js,
Fund.style.js,
FundExplorerHeader.style.js,
FundExplorerPage.style.js,
FundListContent.style.js,
FundLists.style.js,
FundListsTabs.style.js,
Fundsheet.style.js,
FundsheetHeader.style.js,
FundsheetInfo.style.js,
FundsheetProfilePicSection.style.js,
FundsheetSubHeader.style.js,
Group.style.js,
Group.style.js,
GroupContent.style.js,
GroupHeader.style.js,
GroupPageTabs.style.js,
GroupSection.style.js,
KeyInfo.style.js,
ListCreateForm.style.js,
LoginForm.style.js,
MenuPopper.style.js,
MissingIsinDialog.style.js,
NewsCenter.style.js,
NotifiedMembersDialog.style.js,
Overview.style.js,
PageError.style.js,
PageNotFound.style.js,
Performance.style.js,
PremiumBadge.style.js,
PrimaryButton.style.js,
PrivacyPolicy.style.js,
RecipientHeader.style.js,
RedirectToShareclass.style.js,
RequestDocumentsPlaceholder.style.js,
ResetPassword.style.js,
RightDrawer.style.js,
Root.style.js,
SearchTextField.style.js,
Shareclass.style.js,
ShareclassSection.style.js,
ShareclassTable.style.js,
SingleFeedItem.style.js,
Subtitle.style.js,
TableDocuments.style.js,
TermsOfUse.style.js,
Text.style.js,
Thread.style.js,
ThreadActivityDialog.style.js,
ThreadContext.style.js,
TranslatedText.style.js,
UnauthorizedLayout.style.js,
Unsubscribe.style.js,
UploadDueDiligenceDocumentDialog.style.js,
UploadFundList.style.js,
UploadFundListContent.style.js,
UploadFundListForm.style.js,
UploadFundListReport.style.js,
UploadFundListTextArea.style.js,
UploadZone.style.js`
const filesOnGoogleSheet = GOOGLE_SHEET_DATA.split(',\n');

// Algorithm is starting

const files = execSync(`find ~/Workspace/ffyn/front/src -name '*.style.js'`, options);

const filesInArray = files.split('\n');

const filesWithoutPath = filesInArray.map(file => {
  const a = file.split('/');
  const b = a[a.length - 1];
  
  return b;
});

const missingFilesFromGoogleSheet = filesWithoutPath.filter(file => !filesOnGoogleSheet.includes(file));

// End of algorithm

console.log("Add the next files to : https://docs.google.com/spreadsheets/d/16wG5rHvON3RSZprVVcMkCiJRHLDs-iRxlaUhhiv2Vyg/edit#gid=0")
console.log(missingFilesFromGoogleSheet.join('\n'));
